/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author Professor
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaLogin = new javax.swing.JPanel();
        CaixaLogin = new javax.swing.JPanel();
        campo_Nome = new javax.swing.JTextField();
        campo_senha_cadastro = new javax.swing.JTextField();
        titulo_Cadastro = new javax.swing.JLabel();
        titulo_cw_cadastro = new javax.swing.JLabel();
        bt_confimar = new javax.swing.JButton();
        campo_Email = new javax.swing.JTextField();
        campo_CPF = new javax.swing.JTextField();
        campo_Telefone = new javax.swing.JTextField();
        bt_confimar1 = new javax.swing.JButton();
        campo_confirmar_senha_cadastro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TelaLogin.setBackground(new java.awt.Color(5, 10, 25));
        TelaLogin.setPreferredSize(new java.awt.Dimension(862, 461));

        CaixaLogin.setBackground(new java.awt.Color(0, 10, 57));

        campo_Nome.setForeground(new java.awt.Color(204, 204, 204));
        campo_Nome.setText("Nome Completo*");

        campo_senha_cadastro.setForeground(new java.awt.Color(204, 204, 204));
        campo_senha_cadastro.setText("Senha *");

        titulo_Cadastro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titulo_Cadastro.setForeground(new java.awt.Color(255, 255, 255));
        titulo_Cadastro.setText("Cadastro");

        titulo_cw_cadastro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titulo_cw_cadastro.setForeground(new java.awt.Color(51, 51, 255));
        titulo_cw_cadastro.setText("CW");

        bt_confimar.setBackground(new java.awt.Color(51, 153, 255));
        bt_confimar.setText("cadastre-se");
        bt_confimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_confimarActionPerformed(evt);
            }
        });

        campo_Email.setForeground(new java.awt.Color(204, 204, 204));
        campo_Email.setText("E-mail *");
        campo_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_EmailActionPerformed(evt);
            }
        });

        campo_CPF.setForeground(new java.awt.Color(204, 204, 204));
        campo_CPF.setText("CPF *");
        campo_CPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_CPFActionPerformed(evt);
            }
        });

        campo_Telefone.setForeground(new java.awt.Color(204, 204, 204));
        campo_Telefone.setText("Telefone *");
        campo_Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_TelefoneActionPerformed(evt);
            }
        });

        bt_confimar1.setBackground(new java.awt.Color(51, 153, 255));
        bt_confimar1.setText("Cancelar");
        bt_confimar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_confimar1ActionPerformed(evt);
            }
        });

        campo_confirmar_senha_cadastro.setForeground(new java.awt.Color(204, 204, 204));
        campo_confirmar_senha_cadastro.setText("cofirmar Senha *");
        campo_confirmar_senha_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_confirmar_senha_cadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CaixaLoginLayout = new javax.swing.GroupLayout(CaixaLogin);
        CaixaLogin.setLayout(CaixaLoginLayout);
        CaixaLoginLayout.setHorizontalGroup(
            CaixaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CaixaLoginLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(titulo_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo_cw_cadastro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CaixaLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CaixaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_Nome)
                    .addComponent(campo_Email)
                    .addComponent(campo_CPF)
                    .addComponent(campo_Telefone)
                    .addComponent(campo_senha_cadastro)
                    .addComponent(campo_confirmar_senha_cadastro)
                    .addGroup(CaixaLoginLayout.createSequentialGroup()
                        .addComponent(bt_confimar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(bt_confimar1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        CaixaLoginLayout.setVerticalGroup(
            CaixaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CaixaLoginLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(CaixaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo_cw_cadastro))
                .addGap(36, 36, 36)
                .addComponent(campo_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_senha_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_confirmar_senha_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(CaixaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_confimar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_confimar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TelaLoginLayout = new javax.swing.GroupLayout(TelaLogin);
        TelaLogin.setLayout(TelaLoginLayout);
        TelaLoginLayout.setHorizontalGroup(
            TelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaLoginLayout.createSequentialGroup()
                .addContainerGap(441, Short.MAX_VALUE)
                .addComponent(CaixaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        TelaLoginLayout.setVerticalGroup(
            TelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CaixaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TelaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TelaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_confimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_confimarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_confimarActionPerformed

    private void campo_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_EmailActionPerformed

    private void campo_CPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_CPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_CPFActionPerformed

    private void campo_TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_TelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_TelefoneActionPerformed

    private void bt_confimar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_confimar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_confimar1ActionPerformed

    private void campo_confirmar_senha_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_confirmar_senha_cadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_confirmar_senha_cadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CaixaLogin;
    private javax.swing.JPanel TelaLogin;
    private javax.swing.JButton bt_confimar;
    private javax.swing.JButton bt_confimar1;
    private javax.swing.JTextField campo_CPF;
    private javax.swing.JTextField campo_Email;
    private javax.swing.JTextField campo_Nome;
    private javax.swing.JTextField campo_Telefone;
    private javax.swing.JTextField campo_confirmar_senha_cadastro;
    private javax.swing.JTextField campo_senha_cadastro;
    private javax.swing.JLabel titulo_Cadastro;
    private javax.swing.JLabel titulo_cw_cadastro;
    // End of variables declaration//GEN-END:variables
}
